//! Boundary conversion delegates resource and billing invariants to the shared model.
use crate::model::ConfigurationRecord;
use ic_blob_storage::dto::configuration::{
    ServiceBillingInput, ServiceConfigurationInput, ServiceFundingInput, ServiceReadInput,
    ServiceResourceInput,
};
pub(super) fn record(input: &ServiceConfigurationInput) -> ConfigurationRecord {
    ConfigurationRecord {
        version: 1,
        release: env!("CARGO_PKG_VERSION").to_owned(),
        service: input.service,
        operator: input.operator,
        payment_account: input.payment_account,
        namespace: input.namespace,
        max_tenants: input.resources.max_tenants,
        max_object_bytes: input.resources.max_object_bytes,
        max_headers: input.resources.max_headers,
        max_header_bytes: input.resources.max_header_bytes,
        max_chunks: input.resources.max_chunks,
        max_tenant_chunks: input.resources.max_tenant_chunks,
        max_objects: input.resources.max_objects,
        max_tenant_objects: input.resources.max_tenant_objects,
        max_physical_bytes: input.resources.max_physical_bytes,
        max_liability_bytes: input.resources.max_liability_bytes,
        max_tenant_logical_bytes: input.resources.max_tenant_logical_bytes,
        max_references_per_object: input.resources.max_references_per_object,
        max_receipts_per_object: input.resources.max_receipts_per_object,
        max_active: input.resources.max_active,
        max_tenant_active: input.resources.max_tenant_active,
        billing_cashier: input.billing.cashier,
        billing_reserve: input.billing.reserve,
        billing_minimum_balance: input.billing.minimum_balance,
        billing_target_balance: input.billing.target_balance,
        billing_max_gateway_entries: input.billing.max_gateway_entries,
        billing_max_gateway_unique: input.billing.max_gateway_unique,
        funding_allocated: input.funding.allocated,
        funding_reserve: input.funding.reserve,
        funding_max_attempts: input.funding.max_attempts,
        read_sessions: input.reads.sessions,
        read_tenant_sessions: input.reads.tenant_sessions,
        read_reply_bytes: input.reads.reply_bytes,
        read_bytes: input.reads.bytes,
        read_tenant_bytes: input.reads.tenant_bytes,
    }
}
pub(super) fn input(record: &ConfigurationRecord) -> ServiceConfigurationInput {
    ServiceConfigurationInput {
        service: record.service,
        operator: record.operator,
        payment_account: record.payment_account,
        namespace: record.namespace,
        resources: ServiceResourceInput {
            max_tenants: record.max_tenants,
            max_object_bytes: record.max_object_bytes,
            max_headers: record.max_headers,
            max_header_bytes: record.max_header_bytes,
            max_chunks: record.max_chunks,
            max_tenant_chunks: record.max_tenant_chunks,
            max_objects: record.max_objects,
            max_tenant_objects: record.max_tenant_objects,
            max_physical_bytes: record.max_physical_bytes,
            max_liability_bytes: record.max_liability_bytes,
            max_tenant_logical_bytes: record.max_tenant_logical_bytes,
            max_references_per_object: record.max_references_per_object,
            max_receipts_per_object: record.max_receipts_per_object,
            max_active: record.max_active,
            max_tenant_active: record.max_tenant_active,
        },
        billing: ServiceBillingInput {
            cashier: record.billing_cashier,
            reserve: record.billing_reserve,
            minimum_balance: record.billing_minimum_balance,
            target_balance: record.billing_target_balance,
            max_gateway_entries: record.billing_max_gateway_entries,
            max_gateway_unique: record.billing_max_gateway_unique,
        },
        funding: ServiceFundingInput {
            allocated: record.funding_allocated,
            reserve: record.funding_reserve,
            max_attempts: record.funding_max_attempts,
        },
        reads: ServiceReadInput {
            sessions: record.read_sessions,
            tenant_sessions: record.read_tenant_sessions,
            reply_bytes: record.read_reply_bytes,
            bytes: record.read_bytes,
            tenant_bytes: record.read_tenant_bytes,
        },
    }
}
