//! Independent vectors generated by the pinned published Caffeine client.
//! No provider call, upload completion or HTTP header validity is established.

use std::num::{NonZeroU64, NonZeroUsize};

use ic_blob_storage::model::identity::caffeine::{
    CAFFEINE_CHUNK_BYTES, CaffeineContentHasher, CaffeineContentHashes, CaffeineHashError,
    CaffeineHashLimits, CaffeineHeader,
    manifest::{
        CaffeineChunkHash, CaffeineChunkManifest, CaffeineManifestError, CaffeineManifestLimits,
    },
};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    vectors: Vec<Vector>,
}

#[derive(Deserialize)]
struct Vector {
    name: String,
    bytes: usize,
    pattern: Pattern,
    headers: Vec<Header>,
    raw_digest: String,
    provider_root: String,
    chunk_hashes: Vec<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
enum Pattern {
    Abc,
    LinearMod251,
    Zeroes,
}

#[derive(Deserialize)]
struct Header {
    name: String,
    value: String,
}

fn bound(value: usize) -> NonZeroUsize {
    NonZeroUsize::new(value).expect("positive limit")
}

fn fixture() -> Fixture {
    serde_json::from_str(include_str!("fixtures/caffeine-hashing/vectors.json"))
        .expect("independent client vectors")
}

fn verify_vector(vector: &Vector, append_size: usize, reverse_headers: bool) {
    let mut headers: Vec<_> = vector
        .headers
        .iter()
        .map(|header| CaffeineHeader {
            name: &header.name,
            value: &header.value,
        })
        .collect();
    if reverse_headers {
        headers.reverse();
    }
    let mut state = CaffeineContentHasher::new(
        u64::try_from(vector.bytes).expect("vector length"),
        &headers,
        CaffeineHashLimits {
            max_content_bytes: NonZeroU64::new(32 * 1024 * 1024).expect("fixture bound"),
            max_append_bytes: bound(append_size),
            max_headers: bound(8),
            max_header_bytes: bound(1024),
        },
    )
    .expect("bounded hashing");
    let mut buffer = vec![0; append_size.min(vector.bytes)];
    let mut offset = 0;
    while offset < vector.bytes {
        let take = buffer.len().min(vector.bytes - offset);
        for (index, byte) in buffer[..take].iter_mut().enumerate() {
            *byte = match vector.pattern {
                Pattern::Abc => b"abc"[offset + index],
                Pattern::Zeroes => 0,
                Pattern::LinearMod251 => {
                    u8::try_from(((offset + index) * 31 + 7) % 251).expect("byte pattern")
                }
            };
        }
        state
            .append(u64::try_from(offset).expect("offset"), &buffer[..take])
            .expect("append");
        if offset >= CAFFEINE_CHUNK_BYTES {
            // Rejected replays after complete leaves must not disturb either
            // the tree frontier or the partially hashed next leaf.
            assert_eq!(
                state.append(u64::try_from(offset).expect("old offset"), &buffer[..take]),
                Err(CaffeineHashError::UnexpectedOffset {
                    expected: u64::try_from(offset + take).expect("next offset"),
                    actual: u64::try_from(offset).expect("old offset"),
                })
            );
        }
        offset += take;
    }
    let expected = CaffeineContentHashes {
        content_digest: vector.raw_digest.parse().expect("raw digest"),
        provider_root: vector.provider_root.parse().expect("tree root"),
    };
    assert_eq!(state.remaining_bytes(), 0);
    assert_eq!(state.verify(expected), Ok(expected), "{}", vector.name);
}

#[test]
fn published_client_vectors_match_across_chunk_edges_and_uneven_tree_heights() {
    for vector in fixture().vectors {
        // A prime append size crosses provider chunk boundaries repeatedly.
        verify_vector(&vector, 65_537, false);
    }
}

#[test]
fn append_boundaries_and_metadata_order_do_not_change_identities() {
    for vector in fixture().vectors {
        // Exercise exact chunk multiples, multi-chunk appends and header order.
        verify_vector(&vector, CAFFEINE_CHUNK_BYTES * 2, true);
    }
}

fn manifest_limits() -> CaffeineManifestLimits {
    CaffeineManifestLimits {
        max_content_bytes: NonZeroU64::new(32 * 1024 * 1024).expect("bound"),
        max_chunks: bound(32),
        max_headers: bound(8),
        max_header_bytes: bound(1024),
    }
}

fn chunk_hashes(vector: &Vector) -> Vec<CaffeineChunkHash> {
    vector
        .chunk_hashes
        .iter()
        .map(|hash| hash.parse().expect("client leaf"))
        .collect()
}

fn headers(vector: &Vector) -> Vec<CaffeineHeader<'_>> {
    vector
        .headers
        .iter()
        .map(|header| CaffeineHeader {
            name: &header.name,
            value: &header.value,
        })
        .collect()
}

#[test]
fn independent_client_manifests_verify_chunks_in_reverse_order_with_effect_free_retries() {
    for vector in fixture().vectors {
        let leaves = chunk_hashes(&vector);
        let mut metadata = headers(&vector);
        metadata.reverse();
        let manifest = CaffeineChunkManifest::new(
            vector.provider_root.parse().expect("root"),
            u64::try_from(vector.bytes).expect("length"),
            &leaves,
            &metadata,
            manifest_limits(),
        )
        .expect("independent manifest");
        let before = manifest.clone();
        for index in (0..leaves.len()).rev() {
            let index64 = u64::try_from(index).expect("index");
            let offset = index * CAFFEINE_CHUNK_BYTES;
            let expected_length = (vector.bytes - offset).min(CAFFEINE_CHUNK_BYTES);
            assert_eq!(manifest.chunk_bytes(index64), Ok(expected_length));
            let mut bytes: Vec<_> = (offset..offset + expected_length)
                .map(|at| match vector.pattern {
                    Pattern::Abc => b"abc"[at],
                    Pattern::Zeroes => 0,
                    Pattern::LinearMod251 => u8::try_from((at * 31 + 7) % 251).expect("pattern"),
                })
                .collect();
            assert_eq!(
                manifest.verify_chunk(index64, &bytes),
                Ok(()),
                "{}",
                vector.name
            );
            // A previous good result cannot make later corrupt bytes pass.
            bytes[0] ^= 1;
            assert_eq!(
                manifest.verify_chunk(index64, &bytes),
                Err(CaffeineManifestError::ChunkHashMismatch)
            );
            bytes[0] ^= 1;
            assert_eq!(manifest.verify_chunk(index64, &bytes), Ok(()));
            if index > 0
                && expected_length == CAFFEINE_CHUNK_BYTES
                && leaves[index] != leaves[index - 1]
            {
                assert_eq!(
                    manifest.verify_chunk(index64 - 1, &bytes),
                    Err(CaffeineManifestError::ChunkHashMismatch)
                );
            }
        }
        assert_eq!(manifest, before);
    }
}

#[test]
fn client_manifest_root_binds_chunk_order_and_metadata_not_just_leaf_membership() {
    for vector in fixture().vectors {
        let leaves = chunk_hashes(&vector);
        let metadata = headers(&vector);
        let root = vector.provider_root.parse().expect("root");
        let length = u64::try_from(vector.bytes).expect("length");
        let create = |leaves: &[CaffeineChunkHash], metadata: &[CaffeineHeader<'_>]| {
            CaffeineChunkManifest::new(root, length, leaves, metadata, manifest_limits())
        };
        let mut changed_metadata = metadata.clone();
        changed_metadata.push(CaffeineHeader {
            name: "X-Fixture",
            value: "changed",
        });
        assert_eq!(
            create(&leaves, &changed_metadata),
            Err(CaffeineManifestError::RootMismatch)
        );
        let mut changed_leaf = leaves.clone();
        changed_leaf[0] =
            CaffeineChunkHash::try_from([0; 32].as_slice()).expect("hash representation");
        assert_eq!(
            create(&changed_leaf, &metadata),
            Err(CaffeineManifestError::RootMismatch)
        );
        if leaves.len() > 1 {
            let mut reordered = leaves.clone();
            reordered.swap(0, 1);
            if leaves[0] == leaves[1] {
                // Equal content has equal leaves; repeated chunks remain valid
                // positions, not duplicates to discard during construction.
                assert!(create(&reordered, &metadata).is_ok());
            } else {
                assert_eq!(
                    create(&reordered, &metadata),
                    Err(CaffeineManifestError::RootMismatch)
                );
            }
            assert_eq!(
                create(&leaves[1..], &metadata),
                Err(CaffeineManifestError::ChunkCountMismatch {
                    expected: u64::try_from(leaves.len()).expect("count"),
                    actual: leaves.len() - 1,
                })
            );
        }
        assert!(create(&leaves, &metadata).is_ok());
    }
}
