[package]
name = "blob-gateway-source"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-blob-storage.workspace = true
serde.workspace = true
blob-test-protocol.workspace = true

[lints]
workspace = true
