[package]
name = "ic-blob-storage-canic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic0.workspace = true
ic-blob-storage = { path = "../ic-blob-storage" }
thiserror.workspace = true
serde.workspace = true

[lints]
workspace = true
