[package]
name = "blob-admission-probe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
blob-test-protocol.workspace = true
candid.workspace = true
ic-blob-storage.workspace = true
ic-blob-storage-contracts.workspace = true
ic-cdk.workspace = true

[lints]
workspace = true
