use crate::provider::onboarding::*;

fn binding() -> AccountLinkBinding {
    AccountLinkBinding {
        cashier: Principal::from_text("72ch2-fiaaa-aaaar-qbsvq-cai").unwrap(),
        caller: Principal::from_text("r7inp-6aaaa-aaaaa-aaabq-cai").unwrap(),
        paid_canister: Principal::from_text("rrkah-fqaaa-aaaaa-aaaaq-cai").unwrap(),
        payment_account: Principal::from_text("ryjl3-tyaaa-aaaaa-aaaba-cai").unwrap(),
    }
}
fn terms() -> AccountLinkTerms {
    AccountLinkTerms {
        daily_limit: NonZeroU128::new(u128::MAX).unwrap(),
        expiration_timestamp: NonZeroU64::new(u64::MAX).unwrap(),
    }
}
#[test]
fn explicit_full_width_terms_match_independent_current_cashier_candid() {
    // Generated by didc against the retained, freshly unchanged provider interface.
    let expected: Vec<u8> = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/caffeine-account-link/request.hex"
    ))
    .trim()
    .as_bytes()
    .as_chunks::<2>()
    .0
    .iter()
    .map(|pair| u8::from_str_radix(std::str::from_utf8(pair).unwrap(), 16).unwrap())
    .collect();
    let input = binding();
    let request = AccountLinkRequest::new(input, terms()).unwrap();
    assert_eq!(request.arguments(), expected);
    assert_eq!(request.binding(), input);
    assert_eq!(request.terms(), terms());
    assert_eq!(request.method_name(), "payment_account_canister_add_v1");
    // Same payer/caller still encodes an explicit payer, never an optional default.
    let self_payer = AccountLinkBinding {
        caller: input.payment_account,
        ..input
    };
    assert_eq!(
        AccountLinkRequest::new(self_payer, terms())
            .unwrap()
            .arguments(),
        expected
    );
}
#[test]
fn unusable_principals_refuse_each_planned_role() {
    for invalid in [Principal::anonymous(), Principal::management_canister()] {
        for role in [
            AccountLinkRole::Cashier,
            AccountLinkRole::Caller,
            AccountLinkRole::PaidCanister,
            AccountLinkRole::PaymentAccount,
        ] {
            let mut input = binding();
            match role {
                AccountLinkRole::Cashier => input.cashier = invalid,
                AccountLinkRole::Caller => input.caller = invalid,
                AccountLinkRole::PaidCanister => input.paid_canister = invalid,
                AccountLinkRole::PaymentAccount => input.payment_account = invalid,
            }
            assert_eq!(
                AccountLinkRequest::new(input, terms()),
                Err(AccountLinkError::InvalidPrincipal(role))
            );
        }
    }
}
